apiVersion: v1
kind: Service
metadata:
  name: sensor2
spec:
  selector:
    app: sensor2
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor2
spec:
  selector:
    matchLabels:
      app: sensor2
  replicas: 1
  template:
    metadata:
      labels:
        app: sensor2
    spec:
      containers:
        - name: sensor2
          image: redd4ford/iot-clouds_lab-4_sensor2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000