apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-static-app
  template:
    metadata:
      labels:
        app: web-static-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: web-static-app
        image: redd4ford/iot-clouds_lab-4_web:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---

apiVersion: v1
kind: Service
metadata:
  name: web-static-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-static-app